#!/usr/bin/env bash
# Deploy aggregator + order-escrow on Stellar **testnet** and write a local env snippet.
#
# Hard rule: refuses mainnet / Public Global passphrase.
#
# Usage:
#   ADMIN=admin ADMIN_G=G... ./scripts/deploy-limit-testnet.sh
#   AGGREGATOR=C... ./scripts/deploy-limit-testnet.sh   # reuse aggregator, deploy escrow only

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
# shellcheck source=lib/testnet-deploy.sh
source "$ROOT/scripts/lib/testnet-deploy.sh"

set_testnet_defaults
ADMIN="${ADMIN:-admin}"
resolve_admin_g

AGG_SCRIPT="$ROOT/contracts/aggregator/deploy-testnet.sh"
ESCROW_SCRIPT="$ROOT/contracts/order-escrow/deploy-testnet.sh"
AGG_ID_FILE="$ROOT/contracts/aggregator/.testnet-aggregator-id"
ESCROW_ID_FILE="$ROOT/contracts/order-escrow/.testnet-escrow-id"
ENV_OUT="${ENV_OUT:-$ROOT/deploy/.env.limit-testnet.local}"

echo "=== 1/2 Aggregator (testnet) ==="
ADMIN="$ADMIN" ADMIN_G="$ADMIN_G" \
  NETWORK_PASSPHRASE="$NETWORK_PASSPHRASE" RPC_URL="$RPC_URL" \
  AGGREGATOR="${AGGREGATOR:-}" \
  bash "$AGG_SCRIPT"

AGGREGATOR=$(tr -d '[:space:]' < "$AGG_ID_FILE")
if [[ ! "$AGGREGATOR" =~ ^C[A-Z2-7]{55}$ ]]; then
  echo "ERROR: missing aggregator id after deploy." >&2
  exit 1
fi

echo ""
echo "=== 2/2 Order escrow (testnet) ==="
ADMIN="$ADMIN" ADMIN_G="$ADMIN_G" AGGREGATOR="$AGGREGATOR" \
  NETWORK_PASSPHRASE="$NETWORK_PASSPHRASE" RPC_URL="$RPC_URL" \
  bash "$ESCROW_SCRIPT"

ESCROW=$(tr -d '[:space:]' < "$ESCROW_ID_FILE")
if [[ ! "$ESCROW" =~ ^C[A-Z2-7]{55}$ ]]; then
  echo "ERROR: missing escrow id after deploy." >&2
  exit 1
fi

mkdir -p "$(dirname "$ENV_OUT")"
cat > "$ENV_OUT" <<EOF
# Generated by scripts/deploy-limit-testnet.sh — testnet only. Do not use on mainnet.
SOROBAN_RPC_URL=$RPC_URL
RPC_URL=$RPC_URL
INDEXER_RPC_URL=$RPC_URL
KEEPER_RPC_URL=$RPC_URL
NETWORK_PASSPHRASE=$NETWORK_PASSPHRASE
KEEPER_NETWORK=testnet
AGGREGATOR_CONTRACT=$AGGREGATOR
ESCROW_CONTRACT=$ESCROW
INDEXER_DB_PATH=./data/analytics-indexer-testnet.db
EOF

echo ""
echo "=== Env snippet written ==="
echo "$ENV_OUT"
echo ""
echo "Source it (example):"
echo "  set -a && source $ENV_OUT && set +a"
echo ""
echo "Contract ids:"
echo "  AGGREGATOR_CONTRACT=$AGGREGATOR"
echo "  ESCROW_CONTRACT=$ESCROW"
echo "Checklist: docs/limit-orders-testnet.md"
